#install-data-hook:
#	@list='$(modules_LTLIBRARIES)'; for p in $$list; do \
#		rm -f $(modulesdir)/$$p ; \
#	done

libdir = $(MOD_PATH)
includedir = $(INCLUDE_PATH)

debug:
	@$(MAKE) CXXFLAGS="$(DEBUG_CXXFLAGS)"
